---

  - name: Add the latest ansible repository
    action: apt_repository repo='ppa:ansible/ansible' state=present

  - name: Add the standard Postgres repository
    action: apt_repository repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

  - name: Add the apt key for the Postgres repository
    action: apt_key url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: update apt cache
    apt: update_cache=yes upgrade=yes

  - name: install git, curl, ansible, python
    apt: name={{ item }} state=present
    with_items:
      - git-core
      - curl
      - python-psycopg2
      - ansible
      - python-pip
      - unzip
      

