---
- hosts: all
  become: true
  become_method: sudo

  vars_files:
    - ./common_vars.yml
    - ./app_vars.yml

  vars:
    mode:               "development"
    db_server:          "localhost"
    swap_size:          "1G"

  roles:
    - Common/common
    - Common/swap
    - Common/webserver   # Install & configure Apache & PHP
    - Common/simple_mail # Mostly for simple alerting, not mass mailing
    - Common/database
    - Common/vhost
